% figure(1)
% plot(pitchangle1.time,pitchangle1.signals.values)
% xlabel('time')
% ylabel('output')
% figure(2)
% plot(pitchangle2.time,pitchangle2.signals.values)
% xlabel('time')
% ylabel('output')
% figure(3)
% plot(pitchangle3.time,pitchangle3.signals.values)
% xlabel('time')
% ylabel('output')
figure(4)
plot(pitchangle4.time,pitchangle4.signals.values)
xlabel(' ±º‰£®s£©')
ylabel('œÏ”¶')